spring:
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/db_pay?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

  kafka:
    template:
      default-topic: "transaction-events"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap:
          servers: localhost:9092
  zipkin:
    base-url: http://localhost:9411


server:
  port: 8030

logging:
  level:
    org:
      hibernate:
        SQL: debug


# docker profile
---
spring:
  cloud:
    config:
      uri: http://config-server:8888
  profiles: docker
datasource:
  url: jdbc:mysql://0.0.0.0:3306/db_pay?serverTimezone=America/Lima&allowPublicKeyRetrieval=true&useSSL=false
  zipkin:
    base-url: http://zipkinserver:9411
  kafka:
    consumer:
      bootstrap-servers: servicekafka:9092
