spring:
  cloud:
    config:
      uri: http://localhost:8888
  zipkin:
    base-url: http://localhost:9411

zuul:
  routes:
    security:
      service-id: security-service
      path: /api/security/**
      url: http://localhost:8010/
      sensitive-headers: Cookie,Set-Cookie
    invoice:
      service-id: app-invoice
      path: /api/invoice/**
      url: http://localhost:8020/
    pay:
      service-id: app-pay
      path: /api/pay/**
      url: http://localhost:8030/
    transaction:
      service-id: app-transaction
      path: /api/transaction/**
      url: http://localhost:8040/

server:
  port: 9090


# docker profile
---
spring:
  cloud:
    config:
      uri: http://config-server:8888
  profiles: docker
  zipkin:
    base-url: http://zipkinserver:9411

zuul:
  routes:
    security:
      url: http://security-service:8010/
    invoice:
      url: http://app-invoice:8020/
    pay:
      url: http://app-pay:8030/
    transaction:
      url: http://app-transaction:8040/