spring:
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=db_security
    username: sa
    password: 1a.2b.3c.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
  zipkin:
    base-url: http://localhost:9411


server:
  port: 8010

logging:
  level:
    org:
      hibernate:
        SQL: debug

config:
  security:
    oauth:
      jwt:
        key: 123456
      client:
        id: webAngular
        secret: 123456
